object_bounding_box_suffix = "_bounding_box"
object_bounding_piece_position_suffix = "_building_piece_placement"
object_nogo_suffix = "_nogo"
object_flag_suffix = "_flag"
object_flag_suffix = "_tech_node"
object_platform_suffix = "_platform"
object_ground_suffix = "_ground"
object_collision3d_suffix = "_collision3d"

collection_windows_suffix = "_windows"
collection_doors_suffix = "_doors"
collection_specials_suffix = "_specials"
collection_lines_suffix = "_lines"
collection_nogos_suffix = "_nogos"
collection_pipes_suffix = "_pipes"
collection_cannons_suffix = "_cannons"
collection_arrow_emitters_suffix = "_arrow_emitters"
collection_docking_points_suffix = "_docking_points"
collection_soft_collisions_suffix = "_soft_collisions"
collection_file_refs_suffix = "_file_refs"
collection_eflines_suffix = "_eflines"
collection_actionVFX_suffix = "_actionVFX"
collection_att_actionVFX_suffix = "_attachmentVFX"
collection_actionVFX2_suffix = "_actionVFX2"
collection_att_actionVFX2_suffix = "_attachmentVFX2"

